---
title: "How are individuals with prediabetes managed in Denmark, and which characteristics are associated with receiving recommended management?"
# Add all contributors here
author:
  - name: David Vadsholt
    affiliation:
      - name: Steno Diabetes Center North Denmark, Aalborg University Hospital, Denmark
      - name: Department of Clinical Medicine, Aalborg University, Denmark
  - name: Johan Røikjer
    affiliation:
      - name: Steno Diabetes Center North Denmark, Aalborg University Hospital, Denmark
      - name: Department of Clinical Medicine, Aalborg University, Denmark
      - name: Department of Endocrinology, Aalborg University Hospital, Denmark
  - name: Jonas Frey Rosborg Schaarup
    affiliation:
  name: Kristina Matthiesen Hansen
    affiliation:
  name: Mikkel Emil Iwanoff Kolind
    affiliation:
  name: Nicklas Rasmussen
    affiliation:
      - name: Steno Diabetes Center North Denmark, Aalborg University Hospital, Denmark
      - name: Department of Clinical Medicine, Aalborg University, Denmark
      - name: Department of Endocrinology, Aalborg University Hospital, Denmark
date: 12-09-2026
format: html
# bibliography: "file/path"
execute:
  echo: true
---

```{r}
#| label: setup
#| include: false

# Include packages here if needed.
```

::: content-hidden
This is a template for writing your protocol in a format that based on features
used in the [Open Science Framework registry](https://osf.io/) for all types of
studies. Because this database is not for observational studies per se, there
are fields that are not relevant for you to fill in. These fields have not been
included in this template. Also, all fields where you have to check a list of
items or similar, have also been excluded from this template.

Please also refer to a relevant reporting checklist (e.g. STROBE) when
describing the study. Find checklists [here](https://www.equator-network.org/).
:::

## Study information

### How are individuals with prediabetes managed in Denmark, and which characteristics are associated with receiving recommended management? A cross-sectional study within the DP-Next prospective cohort

::: content-hidden
*Put in the title of your study. Remember to include your study design in the
title.*
:::

### Description
This study describes the current management of prediabetes in Denmark from the individual perspective, including communication of prediabetes status, follow-up, referral to preventive interventions, and participation in preventive programs.
Secondarily, the study examines which demographic, clinical, and socioeconomic characteristics are associated with receiving recommended management.

::: content-hidden
Overall description of your project. Think of this as what you would reply if a
colleague asked you what your project was about.
:::

### Objectives and hypotheses

Background:

Prediabetes and type 2 diabetes (T2D) represent a growing public health challenge worldwide[@rooney2023]. Large randomized clinical trials have demonstrated that intensive lifestyle interventions, including dietary modification, increased physical activity, and weight reduction, can substantially reduce the risk of progression from prediabetes to T2D[@pan1997; @tuomilehto2001; @reductio2002]. Despite this evidence, Denmark currently has no national clinical guidelines specifically addressing the management of prediabetes. Current practice is generally limited to recommendations for annual HbA1c monitoring, lifestyle modification, and referral to municipal preventive programs when considered appropriate. As a result, the management of prediabetes may vary considerably between healthcare providers and across healthcare sectors.

However, little is known about how individuals actually are managed in routine clinical practice in Denmark. In particular, it remains unclear whether individuals are informed about their diagnosis, offered structured follow-up, or referred to preventive interventions in accordance with current recommendations. Furthermore, characteristics associated with receiving recommended management remain unknown.

The primary aim of this study is to describe the current management of prediabetes in Denmark from the patient's perspective, including communication of the diagnosis, follow-up, referral to preventive interventions, and participation in preventive programs.The secondary aim is to identify characteristics associated with receiving recommended management.

We hypothesise that a substantial proportion of individuals with HbA1c-defined prediabetes have neither been informed of their condition nor offered follow-up or preventive interventions. We further hypothesise that management differs according to age, sex, body mass index, family history of T2D, educational attainment, socioeconomic position, health literacy, personality and region of residence.

::: content-hidden
- Put in a very brief introduction to the topic. Explain the scientific
  background and rationale
- Put in the research aim/objective
- If relevant, list your specific hypotheses
:::

## Design plan

### Study type
This study is an observational study. 

::: content-hidden
**Observational Study**. Data is collected from study subjects that are not
randomly assigned to a treatment. This includes surveys, natural experiments,
and regression discontinuity designs.
:::

### Blinding
No blinding is involved in this study.
::: content-hidden
No blinding is involved in this study.
:::


### Study design
This study is a cross-sectional study within the ongoing DP-Next prospective cohort study. Questionnaire data will be collected as part of the DP-Next questionnaire, to assess the management of prediabetes, including communication of the diagnosis, follow-up, referral to preventive interventions, and participation in preventive interventions.

::: content-hidden
Describe your study design. Typical study designs for observation studies
include cohort, cross sectional, and case-control studies

This question has a variety of possible answers. The key is for a researcher to
be as detailed as is necessary given the specifics of their design. Be careful
to determine if every parameter has been specified in the description of the
study design. There may be some overlap between this question and the following
questions. That is OK, as long as sufficient detail is given in one of the areas
to provide all of the requested information.

Put in overall information about the study design. Key elements of the study
design, the location, relevant dates, periods of recruitment etc. For instance,
include that it is a cohort and cross-sectional (most likely).
:::

## Sampling plan

### Existing data
Data will be obtained as part of the DP-Next prospective cohort study. Participants undergo a questionnaire specifically developed for this study. As of the date of submission, the data exist but we have not yet accessed it, and no analysis has been conducted related to the research plan, including calculation of summary statistics. 

::: content-hidden
**Registration prior to analysis of the data**. As of the date of submission,
the data exist and you have accessed it, though no analysis has been conducted
related to the research plan (including calculation of summary statistics). A
common situation for this scenario when a large dataset exists that is used for
many different studies over time, or when a data set is randomly split into a
sample for exploratory analyses, and the other section of data is reserved for
later confirmatory data analysis.
:::

### Explanation of existing data
The questionnaire contains participant-reported information on communication of prediabetes diagnosis, follow-up, referral to preventive interventions and participation in interventions.
It also includes age, sex, self-reported body mass index, family history of T2D, educational attainment, socioeconomic position, health literacy, personality and region of residence.

::: content-hidden
Describe the data source being used, ideally linking to its website that has
more information.
:::

### Data collection procedures
We will analyse individuals with self-reported HbA1c-defined prediabetes who complete the relevant sections of the DP-Next questionnaire.
Data will be taken from the existing DP-Next questionnaire data package, described in <https://dp-next.github.io/questionnaire-data>. 

::: content-hidden
- If relevant, describe if or how the subset of data was selected or chosen
  participant
- Describe how the exposure was assessed
- Describe how the outcome was assessed
- Describe how the covariates were assessed
:::

### Sample size

For this proposed project, we will include and analyze individuals who completed the DP-Next questionnaire who had self-reported HbA1c-defined prediabetes.

::: content-hidden
Describe the participants. Describe the eligibility criteria and sources of
selection of participants. At this point it may not be possible to know your
sample size.
:::

### Sample size rationale

::: content-hidden
If relevant, describe why you chose the sample size that you did.
:::

## Variables

### Measures variables

The primary exposures are participant characteristics potentially associated with the management of prediabetes, including age, sex, body mass index, family history of T2D, educational attainment, socioeconomic position, health literacy, personality and region of residence.

The primary outcomes are prediabetes management, including communication of the diagnosis, offer of follow-up, referral to preventive interventions, and participation in preventive programs.

::: content-hidden
List the exposure(s), outcome(s), and covariates
:::

## Analysis plan

### Statistical models

Participant characteristics will be summarized using means with standard deviations for continuous variables, when normally distributed. Non-normally distributed continuous variables will be presented as medians with interquartile ranges. Categorical variables will be summarized using frequencies with percentages.

The primary analyses will describe patient-reported management of prediabetes, including communication of the diagnosis, offer of follow-up, referral to preventive interventions, and participation in preventive programs.

Unadjusted and adjusted logistic regression models will be used to examine participant characteristics associated with communication of the diagnosis, offer of follow-up, referral to preventive interventions, and participation in preventive programs. Results will be reported as odds ratios with 95% confidence intervals. Adjusted models will include all participant characteristics.

Statistical analyses will be performed using R (R Foundation for Statistical Computing, Vienna, Austria).

::: content-hidden
Describe your statistical analysis. This is essentially your statistical
analysis plan.

Remember to mention statistical software to be used, analysis of baseline
characteristics, adjustment for confounding, selection of potential confounders,
examined subgroups, how missing data was handled, how loss to follow-up was
addressed and sensitivity analyses.
:::

### Transformations

No transformations are planned for the data.

::: content-hidden
Describe any transformations you will make to the data, such as centering,
recoding, etc. This will likely change during the actual analysis, but at least
here you can give a general idea for what you will do to the data.
:::

### Inference criteria

A two-sided p-value <0.05 will be considered statistically significant. All statistical tests will be two-sided. No adjustment for multiple comparisons, such as the Bonferroni correction, will be applied. The analyses are based on a limited set of prespecified patient characteristics. Applying a Bonferroni correction in this setting would increase the risk of Type II error and may therefore obscure potentially relevant associations.

::: content-hidden
Describe how you will infer that a result is meaningful or not. For instance, if
using p-values, indicate what the threshold is and WHY. Also what steps you are
taking to minimize misclassification/false discovery rate.
:::

### Data exclusion

Individuals without prediabetes will be excluded from the analyses, as the study focuses on individuals with prediabetes. Additionally, participants with missing questionnaire data regarding prediabetes management will be excluded.

::: content-hidden
Describe what data you will exclude and why. For instance, dropping type 1
diabetes since you are only looking at type 2 diabetes. Or how you will handle
outliers.
:::

### Missing data

 Participants with missing questionnaire data regarding prediabetes management will be excluded.

::: content-hidden
Describe how you will handle missing or incomplete data. This will likely change
when you actually do your analysis, but its a good first step.
:::

### Exploratory analyses (optional)

Nothing specific has been planned for exploratory analyses. 

::: content-hidden
Describe any exploratory analyses you will do and that you might report
on/include in the manuscript. Exploratory analysis is on where you have not made
a hypothesis or prediction about, and instead are seeing what patterns or
associations might exist. This could be to help you in your main analysis or it
could be the main aim of your project.
:::

## Other

*add the references here*

## References
